esphome:
  name: analogtelefon
  friendly_name: Analog Telefon

esp8266:
  board: esp01_1m

# Enable logging
logger:
  #baud_rate: 0
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxx"

ota:
  password: "xxxxxxxxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "AnalogTelefon Fallback Hotspot"
    password: "xxxxxxxxxxxxxx"

captive_portal:
# Include your custom component
  - source:
      type: git
      url: https://github.com/2xmy/HomeAssistant
